name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run `npm install -g csv2geojson`
        run: npm install -g csv2geojson

      - name: 'Convert Excel to CSV'
        uses: geolonia/excel-to-csv-action@v0.0.1
        with:
          input_dir: './'

      - name: Convert CSV to GeoJSON
        run: for file in *.csv; { csv2geojson "$file" > ./$(basename -s ".csv" $file).json; }

      - name: Deploy the GeoJSON to `gh-pages`
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          force_orphan: true
